[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
rust-version = "1.58"
authors = ["Saxon Hunt <saxonh.dev@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]